### ISSUE TITLE
Deleted messages dont have `crypto-key` in app_data

### ISSUE THREAD

**Issue by WhiteApfel** [WhiteApfel/Pullkin#1]
```
Traceback (most recent call last):
  File "/home/white/PycharmProjects/Pullkin/pullkin/aioclient.py", line 176, in listen_forever
    await coroutine.asend(None)
  File "/home/white/PycharmProjects/Pullkin/pullkin/aioclient.py", line 140, in __aiolisten_coroutine
    yield await self.__aiolisthen_once(load_der_private_key)
  File "/home/white/PycharmProjects/Pullkin/pullkin/aioclient.py", line 91, in __aiolisthen_once
    crypto_key = self._app_data_by_key(p, "crypto-key")[3:]  # strip dh=
  File "/home/white/PycharmProjects/Pullkin/pullkin/client_base.py", line 233, in _app_data_by_key
    raise RuntimeError("couldn't find in app_data {}".format(key))
RuntimeError: couldn't find in app_data crypto-key
```

app_data value:
```
[
    key: "message_type"
    value: "deleted_messages"
, 
    key: "total_deleted"
    value: "400"
]
```

**Comment by WhiteApfel** [comment]
Message tag: 8 DataMessageStanza

**Comment by WhiteApfel** [comment]
Deleted message will not be processed
